services:
  puppygraph:
    image: puppygraph/puppygraph:stable
    container_name: puppygraph
    environment:
      - PUPPYGRAPH_USERNAME=puppygraph
      - PUPPYGRAPH_PASSWORD=puppygraph123
    networks:
      demo_net:
    ports:
      - "8081:8081"
      - "8182:8182"
      - "7687:7687"
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=nvd_cve
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    networks:
      demo_net:
    ports:
      - "5432:5432"
networks:
  demo_net:
    name: nvd-cve-demo